import 'package:mileage_run/models/aviation.dart';

final List<Aviation> airports = [
  const Aviation(value: 0, text: '東京羽田 / HND'),
  const Aviation(value: 1, text: '東京成田 / NRT'),
  const Aviation(value: 2, text: '大阪伊丹 / ITM'),
  const Aviation(value: 3, text: '大阪関西 / KIX'),
  const Aviation(value: 4, text: '福岡 / FUK'),
  const Aviation(value: 5, text: '千歳 / CTS'),
  const Aviation(value: 6, text: '中部 / NGO'),
  const Aviation(value: 7, text: '那覇 / OKA'),
  const Aviation(value: 8, text: '鹿児島 / KOJ'),
  const Aviation(value: 9, text: '天草 / AXJ'),
  const Aviation(value: 10, text: '神戸 / UKB'),
  const Aviation(value: 11, text: '熊本 / KMJ'),
  const Aviation(value: 12, text: '米子 / YGJ'),
  const Aviation(value: 13, text: '秋田 / AXT'),
  const Aviation(value: 14, text: 'バンコク / BKK'),
  const Aviation(value: 15, text: '台北 / TPE'),
  const Aviation(value: 16, text: '石垣 / ISG'),
  const Aviation(value: 17, text: '宮古 / MMY'),
  const Aviation(value: 18, text: '岩国 / IWK'),
];

final List<Aviation> airlines = [
  const Aviation(value: 0, text: 'JAL'),
  const Aviation(value: 1, text: 'ANA'),
  const Aviation(value: 2, text: 'SKY'),
  const Aviation(value: 3, text: 'SFJ'),
  const Aviation(value: 4, text: 'SNA'),
  const Aviation(value: 5, text: 'ADO'),
  const Aviation(value: 6, text: 'APJ'),
  const Aviation(value: 7, text: 'JJP'),
  const Aviation(value: 8, text: 'VNL'),
  const Aviation(value: 9, text: 'SJO'),
  const Aviation(value: 10, text: 'AK'),
  const Aviation(value: 11, text: 'AKX'),
  const Aviation(value: 12, text: 'TG'),
  const Aviation(value: 13, text: 'CI'),
  const Aviation(value: 14, text: 'EVA'),
  const Aviation(value: 15, text: 'VAX'),
  const Aviation(value: 16, text: 'IT'),
  const Aviation(value: 17, text: 'FW'),
];

final List<Aviation> boardingTypes = [
  const Aviation(value: 0, text: 'Boeing787-9'),
  const Aviation(value: 1, text: 'Boeing787-8'),
  const Aviation(value: 2, text: 'Boeing777-3'),
  const Aviation(value: 3, text: 'Boeing777-2'),
  const Aviation(value: 4, text: 'Boeing767-3'),
  const Aviation(value: 5, text: 'Boeing737-8'),
  const Aviation(value: 6, text: 'Boeing737-7'),
  const Aviation(value: 7, text: 'Boeing737-5'),
  const Aviation(value: 8, text: 'Embraer190'),
  const Aviation(value: 9, text: 'ATR42-6'),
  const Aviation(value: 10, text: 'Airbus A350'),
  const Aviation(value: 11, text: 'Airbus A321'),
  const Aviation(value: 12, text: 'Airbus A320'),
  const Aviation(value: 13, text: 'Boeing747-4'),
  const Aviation(value: 14, text: 'Bombardier DHC8-Q400'),
  const Aviation(value: 15, text: 'Canadian Bombardier CRJ-700'),
];
